### ISSUE TITLE
Pic in flag

### ISSUE THREAD

**Issue by LValla** [Natio/Places#14]
First I thought to allow uploading existing picture in flag because the most important thing is what user thinks...so if a wall remind him ita guitar then he should be able to upload it BUT, FOR NOW, it's OK that limitation because we also defend ourselves by "inappropriate" picture.
And we can focus on other things

**Comment by LValla** [comment]
I'm realizing that if I want to take a screenshot and share it I can't without that feature
so definetily, in the future, not a priority for now, picture sharing, from gallery, is useful
Besides it should be possible to share as for whats app viber FB .... that you can share from whatever part of the smartphone
i.e.
"share via":
WA
places
viber
fb

**Comment by tehzhed** [comment]
I don't know, allowing any kind of media content from the smartphone is
something that breaks one of the things that makes us different from the
others: the genuineness of our posts. Screenshots might be ok, but anything
else breaks the magic, in my opinion.

2015-01-12 11:02 GMT+01:00 LValla notifications@github.com:

**Comment by tehzhed** [comment]
Otherwise, we can differentiate photos taken on-the-go from other media e.g. "media from the gallery" so the user knows what's genuine and what's not...hmm, this needs some thorough discussion, I guess :)

**Comment by LValla** [comment]
agree
Absolutely that
I didn't know how to explain the service to offer
I meant: upload photo or video from every location of smartphone without being forced to open places first
Not all kind of file for sure

**Comment by Natio** [comment]
I like Luca's idea. I think it enhances UX

**Comment by LValla** [comment]
I'm commenting here just to remember myself that is very interesting to see how to do add places to the "share option" list in android together with the already existing app

**Comment by LValla** [comment]
Feature implemented BUT
there's no difference between a picture or a video...so apparently the system will see a video or a picture simply as a phoneMedia...
to fix the matching also on parse
