### ISSUE TITLE
Change images storage format on server

### ISSUE THREAD

**Issue by Natio** [Natio/Places#15]
Now we store flag's pictures as row bytes on a Parse.com table. It means that every time we issue a query on Parse.com we retrieve also pictures data, this consumes CPU time, bandwidth and drains battery. My suggestion is to store pictures (and in future audio and video) as Files [see link](https://parse.com/docs/android_guide#files). In this way we can solve the above mentioned problems.  Parse.com Files can be retrieved asynchronously and cached if needed.

**Comment by LValla** [comment]
Just created on Parse the column for video as well
