### ISSUE TITLE
Delete and report posts

### ISSUE THREAD

**Issue by tehzhed** [Natio/Places#16]
Give the possibility to the user to delete their own posts and report others'.

**Comment by Natio** [comment]
Maybe we should consider a "My flag section" where the user can see/delete all his flags

**Comment by LValla** [comment]
Agree, in the mock up I put on the settings the myFlags section

**Comment by tehzhed** [comment]
Agreed, in the meantime, added the possibility to remove your flags nearby.

**Comment by LValla** [comment]
@tehzhed  mmm I'm remembering we said that, for now, it's better not to allow to delete them because we need flags placed for testing
I mean this feature needs to exist, so it's perfect, but maybe we're adding it after second milestone
because if testers will delete posts, we'll loose real information for our tests. Isn't it?

**Comment by Natio** [comment]
I don't think our testers will remove flags (they love us). But I think it is an important feature because it might be frustrating if you can't delete a flag. Think about a tester that posted a flag with misspelled text

**Comment by tehzhed** [comment]
Also, some of those flags are clearly tests to see if the app is working. Myself, and I believe all the users, find frustrating to see tons of posts with random characters in them. Plus, I  agree with @Natio. I don't see people deleting posts randomly, but mostly just for typos and badly-taken pictures (which is kind of cleaning up the database from non-valuable data, so it's a good thing for everybody;).

**Comment by LValla** [comment]
@tehzhed @Natio Ok right.
Let's do like that, and what about the possibility of editing a post? Can user do that? And from where?
home or in the place?

**Comment by Natio** [comment]
I propose delete from everywhere but edit only in place

**Comment by tehzhed** [comment]
I don't know, I think it's inappropriate to edit Flags. After all, we are sharing contextualized memories and thoughts, and doesn't make any sense to say that something happened or was thought somewhere, in a precise context, and give the user the possibility to update it, in different time, place and state of mind. Instead, they are very free to delete it, but the nice thing is that everything that appears in Places, is immutable, as that moment it was taken in.

**Comment by LValla** [comment]
That's true, agree
Maybe we can think of a countdown
Like after having placed a flag, if you see that actually there is a mistake you have some minutes to correct it
I'm starting to thing also about the deletion....I need to reason... If you can delete, you're deleting history of the place... When u put a sign on a tree...to change it you need:
First, to go there again
And then is not easy to delete something written on a tree or on a stone
Mmm for now I'd think of a countdown, 
FB own all our information, whatsapp as well
So we could be the holders just of the history of places ;)
For now that's the idea....but I need some more time
Thanks to all
