### ISSUE TITLE
We should store reports in a table

### ISSUE THREAD

**Issue by Natio** [Natio/Places#20]
We should create a table in Parse.com that stores all reports instead of using a column in Posts table

**Comment by LValla** [comment]
Created class ReportedPosts on Parse.com
It also contains the ReportAuthorID as an array entry

**Comment by tehzhed** [comment]
There's no implementation for this yet, let's reopen the case ;) also, what about this: the reported Flags that are in the end removed go on a different table, but only after either they reach a given amount of reports, or we decide that they are effectively offensive/inappropriate (NLP or manually). Reporting a Flag doesn't necessarily mean that it should be deleted.

**Comment by Natio** [comment]
yep. I agree. They should go in the same table as deleted flags. With a value that indicates why a flag has been removed (user or report ). I can work on that in the next days

**Comment by tehzhed** [comment]
@Natio I like this.
