### ISSUE TITLE
Bug movable map

### ISSUE THREAD

**Issue by LValla** [Natio/Places#21]
It happened again that I was able to move the map
I think it depends on a location problem
When the device's position is not recognize then I don't have the button to see where I am and beside I can move the map...but I'm not able to say wether I can see flags or not around me...I think not because places doesn't know where the smartphone is...so doesn't know what to show

**Comment by michead** [comment]
bug should be fixed in the latest version of the code, let me know

**Comment by tehzhed** [comment]
solved by @michead .
