### ISSUE TITLE
Bundle size exceeded, failed binder transaction -- picture (or video) won't be stored

### ISSUE THREAD

**Issue by michead** [Natio/Places#22]
E.g. when taking a picture (or a video), it may not be stored because of this. 
Bundles cannot exceed a certain size, we should work on lightening this load.
Line from logcat: E/JavaBinder﹕ !!! FAILED BINDER TRANSACTION !!!

**Comment by Natio** [comment]
we can think about using files, in this way we can just save file path in the bundle

**Comment by michead** [comment]
Agree, I would go for file paths
