### ISSUE TITLE
Bag Idea

### ISSUE THREAD

**Issue by LValla** [Natio/Places#27]
Just a suggestion from a user to deepen ( Not a priority for now )
The idea is to be able to collect something in some way. Like souvenir feature.

**Comment by tehzhed** [comment]
More details about this idea?

**Comment by LValla** [comment]
We will have to think about it in the future: should be the possibility to "collect" something about the flag
And that is interesting for a couple of reasons:
1. when a user discovered an interesting flag he wants to save something about it, it's normal, and we should provide that possibilty ( maybe just a little preview that can look at, when he is at home, or something else )
2. let's say that there are events on that flag, like the uses commented it and someone else commented it, well he could receive a notification like: There are new activities on that flag.

we can call the function: souvenir, when I thought bag I was thinking of PokemonGameBoy where Ash has its bag =)

That was just a brain storming for now

**Comment by LValla** [comment]
[UPDATE]
Flags that go inside the bag:
- flags wowed
- flags commented
- flags explicitly added to the bag through a button
- extra:
  Comments on flags added from HOME, not in place, maybe should be set as "not in place" exactly as uploading a picture
