### ISSUE TITLE
Show users names on parse table

### ISSUE THREAD

**Issue by LValla** [Natio/Places#28]
column with name, besides FBid

**Comment by Natio** [comment]
I agree. The problem is that usernames change, we have to find an efficient way to update usernames

**Comment by tehzhed** [comment]
I agree that it would be interesting, but updating is not really a problem,
username is just to have a quick reference for knowing who updated what,
but in case we are really interested in knowing somebody's identity, we can
use the fbid.

**Comment by tehzhed** [comment]
Implemented.
