### ISSUE TITLE
Limit video length and quality

### ISSUE THREAD

**Issue by Natio** [Natio/Places#30]
Parse files can not be bigger than 10MB. Different devices will record videos at a different frame rate. Therefore we should find a good compromise between length and quality.

**Comment by Natio** [comment]
I've added an activity (VideoCaptureActivity) that handles video capture. Now we can control length and quality. 

Current settings are:
Video: 20fps, 640x480, 1229.55kbps, H.264
Audio: 96kbps, AAC
In this way we can store 60 seconds in 10MB.

VideoCaptureActivity needs a better UI!

**Comment by LValla** [comment]
OK, I'll take a look of the new activity and see how to optimize the interface
Thanks
