### ISSUE TITLE
Discover mode

### ISSUE THREAD

**Issue by LValla** [Natio/Places#41]
ability to see the presence of certain flag without the content
suggestion to move closer to see their content

further option:
smart algorithm which suggest flags based on users' interests

**Comment by LValla** [comment]
the discover mode comes from the "distance filter" implementaiton
this feature will be the basis for the Treasure Hunt as well!!

**Comment by LValla** [comment]
@tehzhed Discover mode implemented
Do we want to make it "optional":
Activate discover mode?
"Columbus Mode" ? <3

**Comment by tehzhed** [comment]
Done! ;)
