### ISSUE TITLE
Lost Facebook credentials when sharing pic

### ISSUE THREAD

**Issue by tehzhed** [Natio/Places#43]
It happens sometimes that, when sharing a picture, it can't be uploaded because Facebook credentials are lost.

**Comment by LValla** [comment]
that's true BUT ... this is not important for now since we're focusing energies on using the NEW login ;)
So it's better to invest time on the new login option loosing, for the moment, the friends filter that we are going to use in another way in the future

**Comment by tehzhed** [comment]
Sure, but this is not about Facebook, this is about the fact that probably something bad happens in the background (Android cleaning up resources?) so it is something worth investigating anyway ;)

**Comment by LValla** [comment]
WoW
( instead of a "+1" or "Like" =) .... I'm starting to use Places terminology ;) )
