### ISSUE TITLE
Private Flags

### ISSUE THREAD

**Issue by tehzhed** [Natio/Places#44]
Allow user to post Flags that can be visible only to them.

**Comment by LValla** [comment]
Oh yes, I've that on the document, I forgot to write here. Some details about the idea:
Use a password
I want to leave something for my girlfriend just close to her accommodation. I can place the flag and "protect" it with a password shared only with her.

**Comment by tehzhed** [comment]
Also, passwords might be great also for things like treasure hunts.

**Comment by LValla** [comment]
Yes in fact I deeply think that:
private flags + discover mode = TreasureHunt !
Oh Yeah!
