### ISSUE TITLE
"I Placed here!" post on Facebook and Twitter

### ISSUE THREAD

**Issue by tehzhed** [Natio/Places#45]
According to the user feedback, would be nice to have the possibility to post on Facebook or Twitter a quick note telling the world that the user just left a Flag somewhere in the world.

**Comment by LValla** [comment]
It would be nice idea!
But it's not the moment, we're not ready.
First we need to have more social interaction inside Places itself, and then provide features like this one, to increase the interest in the app, and reach more users.
But we still need to make Places a real new social network.
BTW good point! We won't forget about that !

**Comment by LValla** [comment]
- it's possible to share in every social!
- places has now its own social features (wows, comments)
