### ISSUE TITLE
Background_crash

### ISSUE THREAD

**Issue by LValla** [Natio/Places#8]
"Ho notato che ogni tanto però crasha mentre è in background, succede quando attivo\disattivo la localizzazione. Se riapro Places dopo il crash funziona tutto correttamente."
Fabio Samsung s4 android 4.4.4

**Comment by Natio** [comment]
We should find a way to get stack traces from testers

**Comment by tehzhed** [comment]
As of now, every crash is being tracked because the logcat output is being stored as a text file on the phone. This is a quick hack so to be able to read the log also on-the-fly. Something more handy and simple to collect could prove useful though.

**Comment by Natio** [comment]
We could use this http://blog.parse.com/2014/12/09/introducing-parse-crash-reporting-2/ but last time I tried I could successfully add it.

**Comment by tehzhed** [comment]
As far as you know, did anybody experience any crash with the latest version?

**Comment by LValla** [comment]
yesterday someone told me he knew that there are problem with lollipop
but he wasn't able to say which version were...
To which version do you refer exactly?

**Comment by tehzhed** [comment]
I know there are some issues with some users running Lollipop, but I don't know much more either. I'm talking about PlacesBeta.apk, released to testers on January 20 at 12:44pm.
